line 9 assertion failed: 10 == foo(): FAILURE
line 10 assertion failed: 12 == foo(): SUCCESS
